### ISSUE TITLE
[BE] - Enable HTTPS on server

### ISSUE THREAD

**Issue by michalpalenkar** [dropout1692/VezmiTo#35]
Mixed Content: The page at 'https://dropout1692.github.io/VezmiTo/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://dpt.wtf:1337/vezmito/api/v1/submissions/get'. This request has been blocked; the content must be served over HTTPS.

**Comment by dropout1692** [comment]
Done.
